image: twobrowin/runners:kubectl-buildah

deploy:
  script:
  - buildah --storage-driver=vfs bud -t tuned-keycloak .
  - buildah push --storage-driver=vfs --tls-verify=false --creds $DOCKER_PUSH_CREDS tuned-keycloak $DOCKER_PUSH_REGISTRY/tuned-keycloak:latest
  - kubectl --kubeconfig $KUBECTL_CONFIG --token $KUBECTL_USER_TOCKEN apply -f keycloak.yaml
