image: twobrowin/runners:alpine-kubectl-buildah-envsubst

stages:
- deploy

envsubst:
  stage: envsubst
  script:
  - envsubst -i keycloak.yaml -o keycloak-PREPARED.yaml
  artifacts:
    paths:
    - keycloak-PREPARED.yaml
    expire_in: 30 minutes

deploy:
  stage: deploy
  script:
  - kubectl --kubeconfig $KUBECTL_CONFIG --token $KUBECTL_USER_TOCKEN apply --record -f keycloak-PREPARED.yaml