image: twobrowin/runners:alpine-kubectl-buildah-envsubst

stages:
- envsubst
- deploy

envsubst:
  stage: envsubst
  script:
  - envsubst -i volumes.yaml -o volumes-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}.yaml
  - envsubst -i keycloak.yaml -o keycloak-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}.yaml
  artifacts:
    paths:
    - keycloak-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}.yaml
    expire_in: 30 minutes

deploy:
  stage: deploy
  script:
  - kubectl --kubeconfig $KUBECTL_CONFIG --token $KUBECTL_USER_TOCKEN apply --record -f volumes-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}.yaml
  - kubectl --kubeconfig $KUBECTL_CONFIG --token $KUBECTL_USER_TOCKEN apply --record -f keycloak-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}.yaml